Добавил реализацию добавления поста.
htmlacademy-php/6616-readme-12 pull request #11
Opened 2021-11-07 20:14 UTC by alexeyzuby

Сделал добавление поста по формам. Но там есть один нюанс. Почему то плагин dropzone работает весьма криво и добавление файла стало работать только после того, как я разрешил нажимать на поле "Перетащите сюда фото". На закидывание или добавление через кнопку "Выбрать фото" ничего не происходит, будто input не получает файл. Но в целом вся логика работает.

2021-11-08 18:41 UTC, olegmifle requested changes

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +        $link = $_POST[ 'typeName' ] === 'link' ? $_POST[ 'url' ] : '';
Нужно экранировать входящие данные.
Зачем пробелы между название ключа и скобками?

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +                $tags = array_diff($tagsArray, array(''));
```suggestion
                $tags = array_diff($tagsArray, []);
```
Начиная с php 5.6 можно использовать сокращённый синтаксис массивов

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +        if (empty($errors)) {
```suggestion
        if (count($errors) === 0) {
```
empty слишком много кейсов покрывает. Лучше его не использовать, что бы не получить сюрпризов.

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +                    $image = '../uploads/' . $fileName;
Путь лучше вынести в общую переменную или константу т.к. используется в разных местах

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +                        if ($oldTag[ 'name' ] === $tagValue) {
Слишком глубокая вложенность, максимум 3.

2021-11-08 18:41 UTC, olegmifle commented on add.php
> +                    $insertTagsSql = 'INSERT INTO hashtag (name) VALUES ' . implode(',', $insertTags);
Выноси действия за пределы запроса, т.к. implode(',', $insertTags) в какую-то переменную посредник. Так легче читается.

2021-11-08 18:41 UTC, olegmifle commented on validation.php
> +    function validateUrl($url): string
У тебя тут и ссылка проверяется, и файл. Нужно разделять.

2021-11-08 18:41 UTC, olegmifle commented on validation.php
> +    function validateAuthor($author): string
По сути все 3 функции одинаковые. Объедини в одну тогда

2021-11-12 09:34 UTC, olegmifle commented on validation.php
> +    function validateAuthor($author): string
Это не сделано.

2021-11-12 09:35 UTC, olegmifle requested changes
А что изменилось?)

2021-11-17 18:35 UTC, alexeyzuby commented
Прости, я закрывал поэтапно замечания, но не пушил их

2021-11-18 16:05 UTC, olegmifle requested changes

2021-11-18 16:05 UTC, olegmifle commented on add.php
> +                        if (in_array($oldTag['name'], $tags)) {
Опять уровень вложенности слишком глубокий. Разбей лучше код по функциям.

2021-11-18 16:05 UTC, olegmifle commented on add.php
> +                            array_push($tagsIds, intval($oldTag['id']));
Нет смысла array_push использовать. Делай просто $tagsIds[] = '...';

2021-11-18 16:16 UTC, alexeyzuby commented on add.php
> +                        if (in_array($oldTag['name'], $tags)) {
Сейчас разобью и запушу

2021-12-01 11:01 UTC, ademaro approved these changes
Массивный рефакторинг, в целом всё круто, про папку /view поговорим на консультации 💪🏼

2021-12-01 11:02 UTC, merged