Пишем первую функцию
htmlacademy-php/6616-readme-12 pull request #4
Opened 2021-06-21 14:34 UTC by alexeyzuby

2021-06-23 05:06 UTC, olegmifle requested changes

2021-06-23 05:06 UTC, olegmifle commented on index.php
> +function trim_content(string $content, int $length_limit = 300): string
По [PSR-2](https://www.php-fig.org/psr/psr-2/) название переменных, функций, методов должно быть в camelCase стиле

2021-06-23 05:06 UTC, olegmifle commented on index.php
> +    $trimmed_content = implode(' ', $trimmed_words);
Кажется, тут может быть проблема, что знаки препинания будут с пробелами с двух сторон.

2021-06-23 06:58 UTC, alexeyzuby commented on index.php
> +function trim_content(string $content, int $length_limit = 300): string
Поменял

2021-06-23 07:11 UTC, alexeyzuby commented on index.php
> +    $trimmed_content = implode(' ', $trimmed_words);
В моем случае все знаки препинания при использовании explode в массиве получаются частью слова, и во время обратной компоновки через implode так и остаются в рамках своих же слов, будь то запятая, кавычки, двоеточие, восклицательный знак и т.д. То есть если у знака изначально пробел с двух сторон, то только тогда получится данный кейс. Нужно исключать в принципе появление пробела до знака препинания, если в оригинальном тексте допущен лишний пробел? Или сам факт того, что знаки препинания являются частью слова при explode уже является ошибкой?

2021-06-25 11:40 UTC, alexeyzuby commented on index.php
> +        $contentLength += mb_strlen($word) + 1;
Заменил strlen на mb_strlen, ибо он считал 1 символ как 2. Получалось, что обрезаться текст начинал уже со 150 символов.
Так же решил добавлять к сумме $contentLength + 1 на каждой итерации, чтобы учитывались пробелы после слов. Заметил, что без этого финальное количество символов в обрезанном тексте может превышать далеко за 300.

2021-06-25 11:59 UTC, olegmifle approved these changes

2021-06-25 11:59 UTC, merged